import React from "react";
import Aboutus from "../images/about.webp";
import Calender from "../images/calendar_white.svg";
import WhyImg from "../images/why_choose_us.webp";
import professional1 from "../images/professional.svg";
import professional2 from "../images/comprehensive.svg";
import professional3 from "../images/patient.svg";
import professional4 from "../images/facilities.svg";
import doct1 from "../images/doctor11.webp";
import doct2 from "../images/doctor12.webp";
import doct3 from "../images/doctor13.webp";
import { FaFacebookF } from "react-icons/fa6";
import { FaInstagram } from "react-icons/fa";
import { FaXTwitter } from "react-icons/fa6";
import Galleryimg from "../images/gellerybanner_img.webp";
import galleryimg1 from "../images/portfolio_4_lg.jpeg";
import galleryimg2 from "../images/portfolio_2_lg.jpeg";
import galleryimg3 from "../images/portfolio_3_lg.jpeg";
import galleryimg4 from "../images/portfolio_5_lg.jpeg";
import galleryimg5 from "../images/gallery12.jpg";
import galleryimg6 from "../images/gallery10.jpg";
import galleryimg7 from "../images/galleryimg9.jpg";
import galleryimg8 from "../images/gallery11.jpg";
import galleryimg9 from "../images/gallery14.jpg";
import galleryimg10 from "../images/gallery15.jpg";
